name: proektoria
description: Guide to the forum Proektoria with a schedule, map and many other useful features

version: 1.0.0+1

environment:
  sdk: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter
  rect_getter: ^0.0.1
  infinite_listview: ^1.0.1+1
  flutter_svg: ^0.15.0
  photo_view: ^0.9.0
  fluttertoast: ^3.1.3
  outline_material_icons: ^0.1.1
  shared_preferences: ^0.5.4+5
  intl: ^0.16.0
  sticky_headers:
    git:
      url: git://github.com/sqxx/flutter_sticky_headers_ex.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/directions/
    - assets/floors/
  fonts:
    - family: CeraPro
      fonts:
        - asset: assets/fonts/CeraPro-Black.ttf
        - asset: assets/fonts/CeraPro-BlackItalic.ttf
        - asset: assets/fonts/CeraPro-Bold.ttf
        - asset: assets/fonts/CeraPro-BoldItalic.ttf
        - asset: assets/fonts/CeraPro-Italic.ttf
        - asset: assets/fonts/CeraPro-Light.ttf
        - asset: assets/fonts/CeraPro-LightItalic.ttf
        - asset: assets/fonts/CeraPro-Medium.ttf
        - asset: assets/fonts/CeraPro-MediumItalic.ttf
        - asset: assets/fonts/CeraPro-Regular.ttf
        - asset: assets/fonts/CeraPro-Thin.ttf
        - asset: assets/fonts/CeraPro-ThinItalic.ttf