name: proektoria
description: Guide to the forum Proektoria with a schedule, map and many other useful features

version: 1.0.0+1

environment:
  sdk: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter
  rect_getter: ^0.0.1
  flutter_svg: ^0.13.1
  outline_material_icons: ^0.1.0
  shared_preferences: ^0.5.3+4
  intl: ^0.15.8
  sticky_headers:
    git:
      url: git://github.com/sqxx/flutter_sticky_headers_ex.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
